### ISSUE TITLE
金FBまとめ

### ISSUE THREAD

**Issue by akiumikin** [KoheiNishino/js_practice#3]
## 対象のコミット
下記のコミットが入った時のmasterブランチが対象
9be121fb95e570fee492239699b82448aaaafdb9

## pacage json
OSSとして書いてみるならdiscriptionなどメタ情報を調べて補完しておくといいっす
　・discription/authorなど
　
## tsconfig.json

viewを構成していくと、相対パスでの設定で `../../../../../fileName` など階層が深くなりやすいので、エイリアス的Pathを設定しておくといいですよー

```yml
    "paths": {                  /* A series of entries which re-map imports to lookup locations relative to the 'baseUrl'. */
      "tsRoot/*": ["./src/typescripts/*"],
      "tsRoot": ["./src/typescripts"],
      "styleRoot/*": ["./src/stylesheets/*"],
      "styleRoot": ["./src/stylesheets/"]
    },
```

この設定をする場合には、webpackのコンパイルでも、tsRootがなんなのか教える必要があり、そちらにも設定が必要です。
上記の参考ファイルとしては KoheiNishino さんの所属している会社の Mi... のサービスのコードを読むと良いです。
（publicなので色々伏せます）

## webpack.config.js

練習用なので、不要ではありますが、実運用を考えるとproduction設定とdevelopment設定のファイルを分けて書けるようにしておくと良いです。

こちらも、Mi....のサービスを参考にすると良いかと思います。

まだローダーの設定が少なそうですね。今後に活用していくファイルが増えていくのに合わせて色々なローダーが必要になってきます。css_loader / url_loaderなどですね、利用するファイルの拡張子が増えた時に整理をすると良いかと思います。

## index.html

メタ情報など省略しているところも多い状態かと思います。
それは意図しているものと、意図してないものがあり把握しておくことは重要になるかと思います。

そのためまず、github pagesなどを使ってページを公開してみるのが良いかと思います。
公開した後にサーチコンソールやGAを入れてみれることや、分析系のサイトにいれることで不足点を見つけやすくなります。

## style.css
小さいサービスで完結させる思想のようなので、現状はこの配置でも良さそうです。
この置き方の際にはcssを更新した際にユーザーの手元のcssファイルがキャッシュされて更新されなくなるので、対処方法は考えておいた方が良いでしょう。
このような不具合に近い動きもローカルだと見えないことがあるので、github pagesなど簡易的なホスティングサービスを利用することを進めます。

これまでbootstrapを利用してのコードが多かったと思うので、メディアクエリを使ってレスポンシブに書いてみるのも良さそうですね

## index.ts

まだ現状では、TypeScriptの恩恵をあまり感じられていないところかと思います。
実際にTypeScriptの恩恵を感じ始めるのはファイルのインポートが増えたり、関数の呼び出しが増えてコードの複雑性がましてきた時になるかと思います。

今後の発展としてはAjax通信部分を作ったりしていくと思いますので、その時にRest通信部分のパーツとViewパーツを分けたり、サーバーサイドから帰ってくるデータ形式のtypes定義のファイルを分けたりしてみましょう。
